In [1]:
import numpy as np

In [2]:
list = ([20, 27, 9, 12, 31, 17, 4, 50, 39, 35])

In [3]:
arr = np.array(list)

In [22]:
print(arr * 4)
print(arr.mean())
print(np.median(arr))
print(arr.std())
print(np.argmin(arr))
print(np.argmax(arr))
print(arr[np.argmin(arr)])
print(arr[np.argmax(arr)])
print(np.min(arr))
print(np.max(arr))
print(arr[arr > 20])



[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
6
7
4
50
4
50
[27 31 50 39 35]


In [29]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
matrix = np.array(matrix)
print(matrix.shape)
print(matrix[:, 2])
print(matrix[1])
print(matrix * 2)
matrix.mean

(3, 4)
[17 14 19]
[ 8 21 14  3]
